### ISSUE TITLE
TRACE BACK ERROR

### ISSUE THREAD

**Issue by nikhilsampathrao** [polca/wurst#32] opened 2024-05-03 08:46 UTC
Hello iam trying to update the database by using the brightway2 and wurst while running the write database code iam getting this error can i know how to solve this 
![image](https://github.com/polca/wurst/assets/165164812/de0e93d1-ac8e-47a4-ab92-e010e86f89a7)
![image](https://github.com/polca/wurst/assets/165164812/436c28ac-1c5a-429a-bbab-e77c98bd544e)

**Comment by cmutel** [comment] 2024-05-03 10:08
Duplicate of https://github.com/brightway-lca/brightway2/issues/81. Please only file issues in one place.

**Closed by cmutel** 2024-05-03 10:08 UTC
